import messages from './tag-messages.js';
export default [
    { tag: '物品', intlLabel: messages.物品 },
    { tag: '音乐', intlLabel: messages.音乐 },
    { tag: '太空', intlLabel: messages.太空 },
    { tag: '运动', intlLabel: messages.运动 },
    { tag: '动物', intlLabel: messages.动物 },
    { tag: '食物', intlLabel: messages.食物 },
    { tag: '我的世界', intlLabel: messages.我的世界 },
    { tag: '酷玩乐学', intlLabel: messages.酷玩乐学 },
    { tag: '怪物大战', intlLabel: messages.怪物大战 },
    { tag: '节假日', intlLabel: messages.节假日 },
    { tag: '奇幻', intlLabel: messages.奇幻 },
    { tag: '天气', intlLabel: messages.天气 },
    { tag: '按钮', intlLabel: messages.按钮 },
    { tag: '字母和数字', intlLabel: messages.字母和数字 },
    { tag: '坦克大战', intlLabel: messages.坦克大战 },
    { tag: '建筑', intlLabel: messages.建筑 },
    { tag: '交通', intlLabel: messages.交通 },
    { tag: '捕鱼达人', intlLabel: messages.捕鱼达人 },
    { tag: '植物', intlLabel: messages.植物 },
    { tag: '飞机大战', intlLabel: messages.飞机大战 },
    { tag: '人物', intlLabel: messages.人物 },
    { tag: '试听课', intlLabel: messages.试听课 },
];
